spring:
  application:
    name: mall-gateway
  cloud:
    gateway:
      routes:
        - id: test_router
          uri: http://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: qq_router
          uri: http://www.github.com
          predicates:
            - Query=url,github
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

